# Generated by Django 4.2.8 on 2023-12-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0002_mainthread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainthread',
            name='game_id',
            field=models.IntegerField(unique=True),
        ),
    ]
