# Generated by Django 4.2.8 on 2023-12-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0004_mainthread_age_ratings_mainthread_aggregated_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainthread',
            name='age_ratings',
        ),
        migrations.RemoveField(
            model_name='mainthread',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='mainthread',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='mainthread',
            name='first_release_date',
        ),
    ]
