# Generated by Django 4.2.8 on 2023-12-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0005_remove_mainthread_age_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainthread',
            name='game_engines',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainthread',
            name='genres',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainthread',
            name='involved_companies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainthread',
            name='platforms',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
