# Generated by Django 4.2.8 on 2023-12-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0007_alter_mainthread_game_engines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainthread',
            name='aggregated_rating_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainthread',
            name='game_engines_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainthread',
            name='genres_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainthread',
            name='involved_companies_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainthread',
            name='platforms_visible',
            field=models.BooleanField(default=False),
        ),
    ]
