# Generated by Django 4.2.8 on 2023-12-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0008_mainthread_aggregated_rating_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainthread',
            name='name_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mainthread',
            name='summary_visible',
            field=models.BooleanField(default=True),
        ),
    ]
