# Generated by Django 4.2.8 on 2023-12-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0009_mainthread_name_visible_mainthread_summary_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainthread',
            name='id',
        ),
        migrations.AlterField(
            model_name='mainthread',
            name='game_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
